language: "ko-KR"

reviews:
  profile: "chill"
  high_level_summary: true
  poem: false

  auto_review:
    enabled: true
    drafts: false

  path_filters:
    - "!**/node_modules/**"
    - "!pnpm-lock.yaml"
    - "!.husky/**"
    - "!**/*.woff"
    - "!**/*.woff2"
    - "!**/*.png"
    - "!**/*.jpg"
    - "!**/*.svg"
    - "!**/public/**"

chat:
  auto_reply: true
